version: '3.6'

services:
  nginx_proxy:
    image: nginx:stable
    hostname: nginx-proxy
    container_name: nginx-proxy
    ports:
      - "8081:80"
    env_file: configuration.env
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/proxy.conf:/etc/nginx/conf.d/default.conf

  nginx:
    image: nginx:stable
    hostname: nginx
    container_name: nginx
    ports:
      - "8082:80"
    env_file: configuration.env
    volumes:
      - ./images:/var/www
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
